"""payment sessions and location

Revision ID: 0812e1ca58ba
Revises: 1f1faa80378e
Create Date: 2026-09-06 11:47:03.753430
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0812e1ca58ba'
down_revision: Union[str, Sequence[str], None] = '1f1faa80378e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by_token_id', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_token_id'], ['refresh_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_revoked_at'), 'refresh_tokens', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.add_column('customer_profiles', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('customer_profiles', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.create_index(op.f('ix_customer_profiles_latitude'), 'customer_profiles', ['latitude'], unique=False)
    op.create_index(op.f('ix_customer_profiles_longitude'), 'customer_profiles', ['longitude'], unique=False)
    op.add_column('payments', sa.Column('provider_event_id', sa.String(length=180), nullable=True))
    op.create_index('uq_payments_provider_event_id', 'payments', ['provider_event_id'], unique=True)
    op.add_column('worker_profiles', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('worker_profiles', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('worker_profiles', sa.Column('service_radius_km', sa.Numeric(precision=6, scale=2), nullable=True))
    op.create_index(op.f('ix_worker_profiles_latitude'), 'worker_profiles', ['latitude'], unique=False)
    op.create_index(op.f('ix_worker_profiles_longitude'), 'worker_profiles', ['longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_profiles_longitude'), table_name='worker_profiles')
    op.drop_index(op.f('ix_worker_profiles_latitude'), table_name='worker_profiles')
    op.drop_column('worker_profiles', 'service_radius_km')
    op.drop_column('worker_profiles', 'longitude')
    op.drop_column('worker_profiles', 'latitude')
    op.drop_index('uq_payments_provider_event_id', table_name='payments')
    op.drop_column('payments', 'provider_event_id')
    op.drop_index(op.f('ix_customer_profiles_longitude'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_latitude'), table_name='customer_profiles')
    op.drop_column('customer_profiles', 'longitude')
    op.drop_column('customer_profiles', 'latitude')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
