"""separate worker payout

Revision ID: 1f1faa80378e
Revises: 1efde1628812
Create Date: 2026-09-06 11:32:15.850069
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1f1faa80378e'
down_revision: Union[str, Sequence[str], None] = '1efde1628812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('worker_payout', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'worker_payout')
    # ### end Alembic commands ###
