"""track booking completion time

Revision ID: 33c24d8e8dd1
Revises: 0812e1ca58ba
Create Date: 2026-09-06 12:43:04.904328
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '33c24d8e8dd1'
down_revision: Union[str, Sequence[str], None] = '0812e1ca58ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = sa.inspect(op.get_bind())
    if 'completed_at' not in {column['name'] for column in inspector.get_columns('bookings')}:
        op.add_column('bookings', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    inspector = sa.inspect(op.get_bind())
    if 'completed_at' in {column['name'] for column in inspector.get_columns('bookings')}:
        op.drop_column('bookings', 'completed_at')
    # ### end Alembic commands ###
